[features]
seeds = false
skip-lint = false
[programs.localnet]
blackjack = "C48e3rcZc5urrHWk6kmDh4UcFkW3n5yGr8LzoRydeYKW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/zeref/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
