[features]
seeds = false
skip-lint = false
[programs.localnet]
blackjack_sol = "8SRFsA98f7HikQZusHLEHEqvK26dQXb4XDWSzX2wL8vE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/zeref/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
